codeclimate/codeclimate-services

codeclimate-services.gemspec

* Remove `bin` from executables, as our gem actually doesn't have any executable. Those stuff in `bin` are binstubs. That confused RubyGems and conflicted executable in user's installation.
* Relax Bundler dependency as current version of Bundler is 1.7.x.

Cleanup gem specifications

---

.travis.yml
codeclimate-services.gemspec

* Add Ruby 2.0 and 2.2 to build matrix.
* Use Travis' container infrastructure.
* Add `test-unit` gem because Ruby 2.2 requires it.

Update Travis configuration and add test-unit gem

---

lib/axiom/types/password.rb
test/axiom/types/password_test.rb

The original type inference[1] uses `equal?` which returns `true` when any subclass, including `String`, is passed in. This fixes an issue when a `String` type is mistakenly marked as `Password` type when passed in.
[1]: http://git.io/SXJanA

Fix type inference for Password type

---

codeclimate-services.gemspec

This will allow codeclimate-services to be used with Rails 4.x+

Relax activemodel dependency

---

lib/cc/services/github_pull_requests.rb
service_test.rb
test/github_pull_requests_test.rb

Based on the configuration of the GH PR service, the "test" will check the permissions of the token to comment or post a status.
I attempted to use the same "no-op" API call style check for comments, but it didn't work in the same way: the API returns a 404 in both the case that the token has insufficient scope as well as the case the the case that the PR number doesn't exist (PR #0 is what I attempted to use, other PRs may not exist yet).
The alternative solution -- checking the headers for x-oauth-scopes -- is pretty good. However, I'm also not certain that it's a definitive solution: I believe there's at least one scenario -- a "machine user" with read-only repo access -- where you can have the proper header (with "repo" scope) but still not be able to post a comment. 
/cc @brynary

Check config of GH PR service and test appropriately for status/comment ability

---

lib/cc/service.rb
lib/cc/service/http.rb
lib/cc/service/invocation/with_error_handling.rb
lib/cc/service/response_check.rb
lib/cc/services/asana.rb
lib/cc/services/campfire.rb
lib/cc/services/flowdock.rb
lib/cc/services/github_issues.rb
lib/cc/services/github_pull_requests.rb
lib/cc/services/hipchat.rb
lib/cc/services/jira.rb
lib/cc/services/lighthouse.rb
lib/cc/services/pivotal_tracker.rb
lib/cc/services/slack.rb
lib/cc/services/version.rb
test/asana_test.rb
test/campfire_test.rb
test/flowdock_test.rb
test/github_issues_test.rb
test/github_pull_requests_test.rb
test/helper.rb
test/hipchat_test.rb
test/invocation_error_handling_test.rb
test/invocation_test.rb
test/jira_test.rb
test/lighthouse_test.rb
test/pivotal_tracker_test.rb
test/service_test.rb
test/slack_test.rb
test/support/fake_logger.rb

In order to properly record the data for ServiceEvents in codeclimate
proper, we need to have the calls to the external services return
something useful. This is the first step toward that goal.

Services return the HTTP call's status

---

lib/cc/services/slack.rb

I added text to the interface making it clear that you must enter # before the channel name. If you fail to do so, you'll get a 500. This came up via a recent support case.

Added more descriptive text to the Slack config page.

---

lib/cc/services/github_pull_requests.rb
test/github_pull_requests_test.rb

https://trello.com/c/q3ByzTqY
When analysis for a commit is skipped because a newer commit was pushed
to the branch, we want to set the status to "success" so that it isn't
stuck in a yellow "pending" state, but we also want to indicate that
analysis didn't run on the skipped commit. So we differentiate the
skipped case with a different status message. Also, never add a comment
for a commit that we have skipped, regardless of the config settings.

Update GitHub status description for skipped builds

---

lib/cc/services/github_pull_requests.rb
test/github_pull_requests_test.rb

We forgot to check if user has turned on the `update_status` flag or not before we sends a pending status to GitHub.
This commit includes refactoring, hopefully to cleanup the confusion on conditionals.

Do not send status update if user disable it

---

lib/cc/service/response_check.rb

The Faraday middleware was returning a strongly typed URI object, which caused an exception farther up the stack.

fixes: https://bugsnag.com/code-climate/code-climate/errors/5501f295ad74b742e9bcae53?event_id=550751a0811ff2025a013729#payload

---

lib/cc/services/github_pull_requests.rb

I'm changing the order of these parameters so that the return value of `#update_status` is used instead of `#add_comment`. This hack corrects a bug in which the comment's return value is returned instead of the status.
Of course the opposite bug still persists (the status's return value can now step on the return value of the comment). However, we are removing the commenting feature in the future, and update_status is already the default behavior for new GitHub repos.
A better compromise might be to merge the resulting hashes?
/cc @noahd1

use return value of GithubPullRequest#update_status in update_state_success

---

lib/cc/services/github_pull_requests.rb
test/github_pull_requests_test.rb

Trello: https://trello.com/c/npDQ4rN3/103-record-response-from-sending-commit-status-instead-of-adding-comment-when-both-commit-status-and-comment-are-on
fixes: https://github.com/codeclimate/codeclimate-services/pull/57#discussion-diff-26773616
`GithubPullRequests` were mistakenly returning a false success code in the common case where a comment is already present on the pull request being updated. We should return a success instead.

return true when pull request commenting is enabled and a comment exists

---

codeclimate-services.gemspec
lib/cc/services/github_pull_requests.rb
lib/cc/services/github_pull_requests_presenter.rb
test/github_pull_requests_presenter_test.rb
test/github_pull_requests_test.rb

This is a no-op unless the payload from the CC event includes both
`fixed_issue_count` and `new_issue_count` keys.
https://trello.com/c/f17uUGRd

Show count of new, fixed issues in PR statuses

---

lib/cc/service.rb
lib/cc/services/github_pull_requests.rb
lib/cc/services/github_pull_requests_presenter.rb
service_test.rb
test/github_pull_requests_presenter_test.rb
test/github_pull_requests_test.rb
test/helper.rb
test/service_test.rb

Also - use new nested hash structure to get issue counts from the event payload.
https://trello.com/c/f17uUGRd

Show new PR status message only for repos with beta feature enabled

---

lib/cc/service.rb
test/helper.rb

Since the order of files returned from `Dir[]` is non-deterministic and depends
on OS. See http://ruby-doc.org/core-2.1.2/Dir.html#method-c-glob

Sort paths before requiring them

---

lib/cc/service.rb
test/service_test.rb

Returning `ok: false` sets `working` to `false` on the service document
in the app, which is incorrect when the service isn't being invoked
because it isn't defined for the given event type. Returning `nil` makes
it easier to distinguish between services that are actually not working
and services that are a no-op for a given event.

Return nil when a service doesn't respond to an event

---

lib/cc/service.rb
test/service_test.rb

https://trello.com/c/1QAKfYtf
Distinguish between service invocations that fail and service
invocations that don't run because the service doesn't respond to an
event without returning nil, since nil is an unexpected response in the
middleware.

Flag ignored service invocations

---

lib/cc/formatters/snapshot_formatter.rb
lib/cc/services/slack.rb
test/formatters/snapshot_formatter_test.rb
test/slack_test.rb

https://trello.com/c/FVI4JXBI
Before this change, attempting to send a snapshot to Slack when there
were no alert or improved constants would return nil, which is an
unexpected value in the app. This change checks to see if those changes
exist before attempting to send a snapshot, and if they don't, returns
a hash with ignored: true instead of nil.

Return hash instead of nil when no changes in snapshot

---

lib/cc/presenters/github_pull_requests_presenter.rb
test/github_pull_requests_test.rb
test/presenters/github_pull_requests_presenter_test.rb

Now that this feature is enabled for all repos, we can remove the check

Remove rollout call for quality stats

---

lib/cc/presenters/github_pull_requests_presenter.rb
lib/cc/service.rb
lib/cc/services/github_pull_requests.rb
service_test.rb
test/github_pull_requests_test.rb
test/helper.rb
test/presenters/github_pull_requests_presenter_test.rb
test/service_test.rb

Remove repo configs, as they are not used anymore (and probably not the best way to do this)
**Note: this can't be merged until https://github.com/codeclimate/codeclimate/pull/1075 is deployed**

Remove repo configs

---

lib/cc/services/github_pull_requests.rb
test/github_pull_requests_test.rb

Need to receive `pull_request` events with `failure` states.

Support failure statuses for GitHub

---

lib/cc/formatters/snapshot_formatter.rb
lib/cc/services/slack.rb
test/formatters/snapshot_formatter_test.rb
test/slack_test.rb

This reverts 423b4ea and introduces a better fix. 
Previously, if `snapshot.alert_constants_payload` was present and `snapshot.improved_constants_payload` was not, `send_snapshot_to_slack` would still return `nil`. With this fix, `send_snapshot_to_slack` will always return some response.
One thing to note is that if the snapshot has both alert and improved constants, `receive_snapshot` for Slack will only return the response from the latter, since `@response` is overwritten. This was the case before as well, but this change makes it more obvious.

Fix nil response when sending snapshot to Slack

---

lib/cc/services/github_pull_requests.rb
test/github_pull_requests_test.rb

@codeclimate/review WIP. I wanted to create a more customized message for PR's that error due to incompatible worker versions- particularly engine related.
So, my solution was:
1) add a key to payload that specifies if the worker version was changed (also updated in finalizer)
PR: https://github.com/codeclimate/finalizer/pull/49
2) create two constants for error messages: one default, one specific to worker version issue.
EDIT: Feedback welcome. It's my first time working with `codeclimate-services`. If my approach seems right, I'll add tests.

update failed pr message

---

lib/cc/services/version.rb
pull_request_test.rb

@codeclimate/review This PR bumps the Code Climate Services version from 0.1.0 to 0.2.0, after a change to services and finalizer that lets cc-services now receive an optional `"messages"` key on `@payload` - to provide clarity when analysis fails due to version incompatibility between snapshots. I have tested using the PR event trigger script in `codeclimate-services`.
The PR also makes minor updates to the pull request test, bringing over some clarifying instructions re OAUTH token from a same test in app.
If all looks well, I will bump the version and update `codeclimate/app`.
One note: 
Intent of change was to make error messages more explicit and remove details link when comparisons fail due to analysis version incompatibility between snapshots. 
Default error message:
Analysis fails …

bump version

---

lib/cc/services/github_pull_requests.rb

@codeclimate/review @pbrisbin This PR fixes the placement of a comment that I'd separated from target method.

keep comment with target method

---

lib/cc/helpers/issue_helper.rb
lib/cc/service.rb
lib/cc/services/asana.rb
lib/cc/services/github_issues.rb
lib/cc/services/jira.rb
lib/cc/services/lighthouse.rb
lib/cc/services/pivotal_tracker.rb
test/asana_test.rb
test/fixtures.rb
test/github_issues_test.rb
test/jira_test.rb
test/lighthouse_test.rb
test/pivotal_tracker_test.rb

/cc @codeclimate/review 
This adds an `issue` type for messages sent to external services. I chose to add this new type over adding to `quality`, as `quality` is already used for 2 things (rating changes and refactoring hot spots). 
I realize there is a fair amount of duplicated code here - I'm open to ideas on how to fix that, but I'm not familiar enough with this codebase to make that call right now.
I skipped the following services, as they only deal with transitions:
* Campfire
* Flowdock
* Hipchat
* Slack
Preview on each service:

Add Issue type

---

lib/cc/services/github_issues.rb
lib/cc/services/github_pull_requests.rb
test/github_issues_test.rb
test/github_pull_requests_test.rb

When using GH:E, api.github.com will not be the endpoint used to handle
PRs and issues. We can specify it in the configuration to handle that
case better. Defaulting it to api.github.com means that we do not need
to backfill any data.
@codeclimate/review

Add support for specifying a separate Github base URL

---

lib/cc/services/github_pull_requests.rb

@codeclimate/review 
Edit: now we can actually include the details link for errored PRs instead of deleting it when the snapshot is errored.

don't remove details url for errored PRs

---

lib/cc/services/github_pull_requests.rb

Comments is deprecated, so remove this confusing note

Update hint text for GitHub PR token field

---

lib/cc/services/jira.rb
test/jira_test.rb

- Add a description to the test issue. Organizations often have
descriptions required for issues, meaning that our test fails to
create an issue.
- Change URL of resulting hash. The URL returned from the API is the
REST URL, and is not suitable for redirects.
@codeclimate/review

Improve JIRA service

---

lib/cc/services/github_pull_requests.rb

A change in app has resulted in "0" getting written to the add_comment?
field in service records, which result in undesired comments on PRs.
I'm also seeing these value for the update_status? bit.
Digging deeper, I think we may have a general problem with how bools are being
stored here: I've tried configuring Virtus' bool casting, and looking deeper
into how we read & set things, and I'm not making much progress. This is
effectively a patch to fix affected customer behavior now, to give me some mroe
time to look more deeply into underyling problems.

Specify what is considered true for config

---

lib/cc/service/config.rb
lib/cc/services/asana.rb
lib/cc/services/campfire.rb
lib/cc/services/flowdock.rb
lib/cc/services/github_issues.rb
lib/cc/services/github_pull_requests.rb
lib/cc/services/hipchat.rb
lib/cc/services/jira.rb
lib/cc/services/lighthouse.rb
lib/cc/services/pivotal_tracker.rb
lib/cc/services/slack.rb
lib/cc/services/stash_pull_requests.rb
test/github_pull_requests_test.rb

Virtus depends on the type of attributes being the
appopriate `Axiom` class. This led to incorrect & unexpected results in
app, where other classes with the same name were getting resolved,
causing quiet failures.
I rolled back yesterday's temporary patch & added some small sanity tests as well.
cc @codeclimate/review @pbrisbin

Services Type Coercion

---

lib/cc/services/github_pull_requests.rb
pull_request_test.rb
service_test.rb
test/github_pull_requests_test.rb

This feature is no longer needed.
@codeclimate/review 
Note: this is a substantial behavior change for anyone else relying on the codeclimate-services gem. Discussion IRL suggested we're the only ones using it.

Remove code to comment on Github Pull Requests

---

lib/cc/services/github_pull_requests.rb
test/github_pull_requests_test.rb

Unclear why this is false, but I've gotten feedback a few times that it's confusing.

Turn GH PR update status to true by default

---

lib/cc/services/asana.rb
test/asana_test.rb

This value cannot be nil according to Asana's API.
cc @codeclimate/review

Provide default value for Asana notes

---

lib/cc/helpers/quality_helper.rb
lib/cc/services/asana.rb
lib/cc/services/github_issues.rb
lib/cc/services/jira.rb
lib/cc/services/lighthouse.rb
lib/cc/services/pivotal_tracker.rb
test/github_issues_test.rb

The previous logic ended up saying "Refactor from a ?", which isn't great. This centralizes the title logic, which was implemented in a bunch of places, and emits a simpler title if there is no rating data.
cc @codeclimate/review

Improve refactor ticket title when there is no rating

---

README.md
lib/cc/presenters/pull_requests_presenter.rb
lib/cc/service.rb
lib/cc/services/github_pull_requests.rb
test/github_pull_requests_test.rb

This PR implements support within the GitHub pull request integration for test coverage status updates.
Currently the only valid states are `pending` and `success` but support for `failure` will follow.

Support GitHub PR status updates for test coverage

---

lib/cc/services/github_pull_requests.rb
pull_request_test.rb
service_test.rb
test/github_pull_requests_test.rb

This PR removes configuration options to enable/disable commit status updates on active GitHub pull request integrations. These options made sense when we also supported commenting on pull requests, but since commit status updates are now the only mechanism we use, an active integration should also signify the intent to receive commit status updates.
To honor current configurations, we'll likely need a migration to set active integrations with `update_status=false` to an inactive state.
@codeclimate/review :mag_right:

Remove GH PR update_status and update_coverage_status checks

---

lib/cc/presenters/pull_requests_presenter.rb
lib/cc/services/github_pull_requests.rb
test/github_pull_requests_test.rb
test/presenters/pull_requests_presenter_test.rb

This commit changes the test coverage commit status description from:
`Test coverge for this commit: ##%`
to:
```
You're at X% test coverage
You're at X% test coverage (up X%)
You're at X% test coverage (down X%)
```
@codeclimate/review :mag_right:

Show test coverage percent delta within commit status update

---

lib/cc/presenters/pull_requests_presenter.rb

These two methods on `Numeric` were added in ruby `2.3` and we're
currently using this gem in services that run on ruby `2.2.0`.
Related ruby core feature request: https://bugs.ruby-lang.org/issues/11151
@codeclimate/review :mag_right:

Remove use of Numeric#positive? and Numeric#negative?

---

lib/cc/services/gitlab_merge_requests.rb
test/gitlab_merge_requests_test.rb

This does not need to be configurable, but does need to be on the config
object in order to match CC::PullRequests' interface
@codeclimate/review

Disallow setting the Gitlab context

---

lib/cc/services/github_issues.rb

This follow-redirect behavior was implemented in #97 specifically to
account for some GH API behavior, but as Max very kindly pointed out
recently, we weren't actually using it where we had intended to.
Now we are using it.
cc @codeclimate/review

Respect redirects when creating GH issues

---

lib/cc/pull_requests.rb
lib/cc/services/github_pull_requests.rb
lib/cc/services/gitlab_merge_requests.rb
spec/cc/service/github_pull_requests_spec.rb

Adds new config values to allow reporting PR statuses for only specific
users and/or a percentage of users.
The `author_username` key being used in the payload isn't actually sent
right now: I need to evaluate if there's an existing key we send that is
usable, or if we need to thread this data through on the app side.
cc @codeclimate/review

WIP: Allow rolling out PR status reporting

---

Rakefile

On balance, these warnings aren't valuable. They mostly generate noise for
things we actually prefer and don't consider problematic (e.g. private
attributes). The warnings we do care about will be raised as Rubocop issues.
/cc @codeclimate/review @wfleming @maxjacobson

Don't run specs with warnings enabled

---

.codeclimate.yml
lib/cc/service/http.rb
lib/cc/service/safe_webhook.rb
spec/cc/service/github_issues_spec.rb
spec/cc/service/github_pull_requests_spec.rb
spec/cc/service/gitlab_merge_requests_spec.rb
spec/cc/service/safe_webhook_spec.rb
spec/spec_helper.rb
spec/support/resolv_helper.rb

Implements an IP address blacklist to mitigate users configuring a Webhook to
POST to one of our (presumably unauthenticated) internal services.
http://blog.fanout.io/2014/01/27/how-to-safely-invoke-webhooks/#ip-address-blacklisting
- Resolve the configured value to its canonical IP address
- Compare that against the blacklist
- Rewrite the request to be for that verified IP with an explicit Host header
This is disable-able via ENV since CC:E will be posting to local services
intentionally.
/cc @codeclimate/review @brynary
TODO:

Add SafeWebhook concept

---

.codeclimate.yml
lib/cc/fixed_resolv.rb
lib/cc/service/http.rb
lib/cc/service/safe_webhook.rb
spec/cc/service/safe_webhook_spec.rb
spec/cc/service_spec.rb
spec/spec_helper.rb
spec/support/resolv_helpers.rb

/cc @codeclimate/review
Found a way to do the SafeWebhook thing that doesn't require re-writing the request,
but does ensure the Resolv done when checking if internal gives the same answer
when we ultimately connect.
TODO:

SafeWebhook - Take 2

---

lib/cc/presenters/pull_requests_presenter.rb
spec/cc/presenters/pull_requests_presenter_spec.rb
spec/cc/service/github_pull_requests_spec.rb
spec/cc/service/gitlab_merge_requests_spec.rb

Our messages are being truncated to, e.g. "58.02% test coverage (+1..."
The status already has a name of "codeclimate/coverage", so I think with
context this will be sufficient information.
Another idea considered: "58.02% cov (+1%)" or "58.02% (+1%) cov". We use similar language in the extension ("100% cov") so maybe that's good for consistency. Thoughts welcome!
@codeclimate/copy @codeclimate/review

Shorten test coverage status

---

lib/cc/presenters/pull_requests_presenter.rb
spec/cc/presenters/pull_requests_presenter_spec.rb
spec/cc/service/github_pull_requests_spec.rb
spec/cc/service/gitlab_merge_requests_spec.rb
spec/cc/service/stash_pull_requests_spec.rb

They're being truncated on GitHub. We recently shortened the test
coverage statuses as well, and today this has been popping out at me.
I don't believe they're actually displayed on GitLab, so it's OK that
we're affecting that.
I'm less sure about Stash.
@codeclimate/review @codeclimate/copy

Shorten Code Climate analysis statuses

---

lib/cc/services/asana.rb
spec/cc/service/asana_spec.rb

Asana is deprecating their API Key access, as reported by a helpful
user.
https://asana.com/developers/documentation/getting-started/auth#api-key
We confirmed with their support team that they're planning to drop
support for API Key authorization in "early 2017".
This PR introduces support for authorizing with personal access tokens,
and attempts to nudge users in that direction gently. I think we'll need
to make a plan about how to migrate existing repos over.

Support authorizing asana requests via tokens

---

lib/cc/presenters/pull_requests_presenter.rb
spec/cc/presenters/pull_requests_presenter_spec.rb

@codeclimate/review 
Supports https://github.com/codeclimate/api/pull/149
I considered letting the client construct and pass the message, but thought this approach was a little more restricting in a good way. Thoughts welcome
I also considered, initially, passing the approval_id, but I don't think we want this gem to know about all of our data types.

Change success message when approved_by present

---

codeclimate-services.gemspec

Many tools now require >= 0.9. We should work with that.

Loosen faraday dependency

---

lib/cc/service/http.rb
spec/cc/service/jira_spec.rb

- At some point Faraday stopped ignoring an :adapter being passed in its
initial options and started raising (we'll #delete it out)
- The stubs are now more specific about trailing slashes (we'll add
them)
This gets things green with a ::Fixnum warning from nokogiri, which I'm
hoping will go away when I update that dependency in the next PR.

Make master green again

---

codeclimate-services.gemspec

In order to address
https://github.com/sparklemotion/nokogiri/issues/1615, we need to
upgrade to nokogiri-1.7.1. Applications also depending on this gem are
in conflict unless this version constraint is loosened.

Loosen nokogiri dependency

---

lib/axiom/types/token.rb
lib/cc/service.rb
lib/cc/services/asana.rb
lib/cc/services/campfire.rb
lib/cc/services/flowdock.rb
lib/cc/services/github_issues.rb
lib/cc/services/github_pull_requests.rb
lib/cc/services/gitlab_merge_requests.rb
lib/cc/services/hipchat.rb
lib/cc/services/lighthouse.rb
lib/cc/services/pivotal_tracker.rb
spec/axiom/types/token_spec.rb

This will make it simpler for us to identify which fields are sensitive
by type, rather than by field name.

Add Token marker type

---

lib/cc/service/http.rb
spec/cc/service_spec.rb

Our usage of Faraday in this library is...unusual.
Faraday does generally respect the proxy & proxy exception settings when
you pass the URL directly to a `conn.post` method or anything like that,
but since we set the URL within this block, that's after Faraday's logic
has decided what the proxy should be, and since at that point Faraday
didn't know what URL we were requesting, it used the default proxy
details.

Respect proxy exceptions

---

lib/cc/services/gitlab_merge_requests.rb
spec/cc/service/gitlab_merge_requests_spec.rb

The V4 endpoint is compatible with our current usage, but we need to use the new url.
source: https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit
Even though HTTP header field names are case-insensitive, the docs reference `Private-Token` vs `PRIVATE-TOKEN`.
source: https://docs.gitlab.com/ee/api/#personal-access-tokens

Update GitLab Merge Requests integration for V4 API

---

lib/cc/presenters/pull_requests_presenter.rb
spec/cc/presenters/pull_requests_presenter_spec.rb

Handle a `nil` value for `covered_percent_delta` from api response.

Don't show total coverage delta if unavailable
